api:
  url: "https://bible-api.com"

server:
  port: 8008

spring:
  datasource:
    type: org.postgresql.jdbc2.optional.PoolingDataSource
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bible_db}
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: bible-api