api:
  url: "https://bible-api.com"

server:
  port: 8008

logging:
  level:
    org.springframework.web: DEBUG

token:
  converter:
    principal-attribute: preferred_username
    resource-id: backend
spring:
  datasource:
    type: org.postgresql.jdbc2.optional.PoolingDataSource
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bible_db}
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: bible-api
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/prueba_arquitectura
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs